#define RELEASE_STRING 9.2.0
#define MAJOR_RELEASE_STRING 9.2
#define BUILD_NUMBER 9.2.0.0110
#define MAJOR_VERSION 9
#define MINOR_VERSION 2
#define PATCH_VERSION 0
#define BUILD_SERIAL_NUMBER 0110
#define VERSION_STRING "9.2.0.0110"
#define PRODUCT_STRING "9.2"
#define PACKAGE_STRING "CUBRID 9.2"

